# ## Configure 'ip' variable to bind kubernetes services on a
# ## different ip than the default iface
# ## We should set etcd_member_name for etcd cluster. The node that is not a etcd member do not need to set the value, or can set the empty string value.

# ## configure a bastion host if your nodes are not directly reachable
# bastion ansible_host=x.x.x.x ansible_user=some_user

kube-master:
  hosts:
    k8s-master1:
      ansible_host: 192.168.83.101
      ip: 192.168.83.101
      etcd_member_name: etcd1

etcd:
  hosts:
    k8s-master1:

kube-node:
  hosts:
    k8s-worker1:
      ansible_host: 192.168.83.201
      ip: 192.168.83.201
      nfs_exports: 
        - "/home/vagrant *(rw,sync,no_root_squash)"
    k8s-worker2:
      ansible_host: 192.168.83.202
      ip: 192.168.83.202

k8s-cluster:
  children:
    kube-master:
    kube-node:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_user: vagrant
    #ansible_ssh_pass: vagrant
    ansible_become_pass: vagrant
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
